# Generated by Django 5.0.2 on 2024-02-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_bookmark_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('director', models.CharField(max_length=120)),
                ('poster', models.ImageField(upload_to='images/')),
                ('plot', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
